import { ImageResponse } from '@vercel/og';
import { NextRequest } from 'next/server';

export const runtime = 'edge';

const TEMPLATES: Record<string, {
  bg: string;
  text: string;
  accent: string;
  pattern?: string;
}> = {
  gradient: { bg: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', text: '#ffffff', accent: '#e2d9f3' },
  sunset: { bg: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', text: '#ffffff', accent: '#fde2e4' },
  ocean: { bg: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', text: '#ffffff', accent: '#d4f4ff' },
  forest: { bg: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)', text: '#ffffff', accent: '#d4f8e8' },
  midnight: { bg: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)', text: '#ffffff', accent: '#a5a3c8' },
  fire: { bg: 'linear-gradient(135deg, #f12711 0%, #f5af19 100%)', text: '#ffffff', accent: '#fff3d6' },
  minimal: { bg: '#ffffff', text: '#1a1a1a', accent: '#666666' },
  dark: { bg: '#0a0a0a', text: '#ffffff', accent: '#888888' },
  blue: { bg: '#1e40af', text: '#ffffff', accent: '#93c5fd' },
  emerald: { bg: '#047857', text: '#ffffff', accent: '#6ee7b7' },
  purple: { bg: '#7c3aed', text: '#ffffff', accent: '#c4b5fd' },
  slate: { bg: 'linear-gradient(135deg, #334155 0%, #1e293b 100%)', text: '#ffffff', accent: '#94a3b8' },
};

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;

  const title = searchParams.get('title') || 'Your Title Here';
  const subtitle = searchParams.get('subtitle') || '';
  const template = searchParams.get('template') || 'gradient';
  const author = searchParams.get('author') || '';
  const logo = searchParams.get('logo') || '';
  const width = parseInt(searchParams.get('w') || '1200');
  const height = parseInt(searchParams.get('h') || '630');
  const fontSize = parseInt(searchParams.get('fontSize') || '60');

  const t = TEMPLATES[template] || TEMPLATES.gradient;

  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          padding: '60px 80px',
          background: t.bg,
          color: t.text,
          fontFamily: 'Inter, system-ui, sans-serif',
        }}
      >
        {/* Top bar */}
        <div style={{ display: 'flex', alignItems: 'center', marginBottom: '30px' }}>
          {logo && (
            <img
              src={logo}
              width={40}
              height={40}
              style={{ borderRadius: '8px', marginRight: '12px' }}
            />
          )}
          {author && (
            <span style={{ fontSize: '22px', color: t.accent, fontWeight: 500 }}>{author}</span>
          )}
        </div>

        {/* Title */}
        <div
          style={{
            fontSize: `${fontSize}px`,
            fontWeight: 800,
            lineHeight: 1.15,
            letterSpacing: '-0.02em',
            maxWidth: '90%',
          }}
        >
          {title}
        </div>

        {/* Subtitle */}
        {subtitle && (
          <div
            style={{
              fontSize: '26px',
              color: t.accent,
              marginTop: '20px',
              fontWeight: 400,
              maxWidth: '80%',
            }}
          >
            {subtitle}
          </div>
        )}

        {/* Bottom decoration */}
        <div
          style={{
            position: 'absolute',
            bottom: '40px',
            right: '60px',
            fontSize: '16px',
            color: t.accent,
            opacity: 0.7,
          }}
        >
          Generated by 10001.ai
        </div>
      </div>
    ),
    { width, height }
  );
}
